$import("mx.containers.Panel");$import("mx.datacontainers.GridEntityContainer");$import("mx.datacontrols.DataGrid");$import("mx.controls.ContextMenu");$import("mx.datacontrols.PageNaviBar");$import("thermalpower.views.mainView");$import("thermalpower.views.mainViewController");$import("thermalpower.views.DataGrid");$import("thermalpower.views.DataGridController");
mx.weblets.WebletManager.register({id:"thermalpower",name:"thermalpower",requires:["ETradePublicUtils/fusionChart"],onload:function(){},onstart:function(a){var b=new thermalpower.views.mainViewController;a.context.rootViewPort.setViewController(b)}});$ns("thermalpower.views");$import("mx.datacontainers.GridEntityContainer");$import("mx.datacontrols.ComplexGrid");
thermalpower.views.DataGrid=function(){var a=$extend(mx.views.View),c={},d=null,e=null,f=null;c.init=a.init;a.init=function(){c.init();var b=new mx.datacontainers.GridEntityContainer({baseUrl:thermalpower.mappath("~/rest/setielineresultn/topTen"),iscID:"-1",primaryKey:"guid",loadMeta:!1});d=new mx.datacontrols.ComplexGrid({alias:"thermalpowerTopTenDataGrid",columns:[{name:"sellername",caption:"\u552e\u70b9\u65b9",editorType:"TextEditor",width:"300"},{name:"contractqty",caption:"\u5408\u540c\u7535\u91cf",
editorType:"TextEditor"},{name:"energy_t",caption:"\u5b8c\u6210\u7535\u91cf",editorType:"TextEditor"},{name:"percentage",caption:"\u5b8c\u6210\u7387",editorType:"TextEditor"}],displayCheckBox:!0,displayPrimaryKey:!1,allowEditing:!1,pageSize:20,displayToolBar:!1,displayRowNumber:!0,height:"40%",width:"100%",displayColSplitLine:!0,entityContainer:b});b=new mx.datacontainers.GridEntityContainer({baseUrl:thermalpower.mappath("~/rest/setielineresultn/lastTen"),iscID:"-1",primaryKey:"guid",loadMeta:!1});
e=new mx.datacontrols.ComplexGrid({alias:"thermalpowerLastTenDataGrid",columns:[{name:"sellername",caption:"\u552e\u70b9\u65b9",editorType:"TextEditor",width:"300"},{name:"contractqty",caption:"\u5408\u540c\u7535\u91cf",editorType:"TextEditor"},{name:"energy_t",caption:"\u5b8c\u6210\u7535\u91cf",editorType:"TextEditor"},{name:"percentage",caption:"\u5b8c\u6210\u7387",editorType:"TextEditor"}],displayCheckBox:!0,displayPrimaryKey:!1,allowEditing:!1,pageSize:20,displayToolBar:!1,displayRowNumber:!0,
height:"40%",width:"100%",displayColSplitLine:!0,entityContainer:b});b=new mx.datacontainers.GridEntityContainer({baseUrl:thermalpower.mappath("~/rest/setielineresultn/averageData"),iscID:"-1",primaryKey:"guid",loadMeta:!1});f=new mx.datacontrols.ComplexGrid({alias:"thermalpowerAverageDataGrid",columns:[{name:"sellername",caption:"\u552e\u70b9\u65b9",editorType:"TextEditor",width:"300"},{name:"contractqty",caption:"\u5408\u540c\u7535\u91cf",editorType:"TextEditor"},{name:"energy_t",caption:"\u5b8c\u6210\u7535\u91cf",
editorType:"TextEditor"},{name:"percentage",caption:"\u5b8c\u6210\u7387",editorType:"TextEditor"},{name:"deviation",caption:"\u76f8\u5bf9\u5e73\u5747\u8fdb\u5ea6\u504f\u5dee",editorType:"TextEditor"}],displayCheckBox:!0,displayPrimaryKey:!1,allowEditing:!1,pageSize:20,displayToolBar:!1,displayRowNumber:!0,height:"40%",width:"100%",displayColSplitLine:!0,entityContainer:b});a.on("activate",a.controller._onactivate)};a.getTopTenDataGrid=function(){return d};a.getLastTenDataGrid=function(){return e};
a.getAverageDataGrid=function(){return f};a.endOfClass(arguments);return a};$ns("thermalpower.views");$import("mx.permissions.Permission");$import("mx.permissions.PermissionAgentClass");$import("thermalpower.views.DetailViewController");$import("thermalpower.views.DataGrid");
thermalpower.views.DataGridController=function(){var a=$extend(mx.views.ViewController);a.getView=function(){if(a.view==null)a.view=new thermalpower.views.DataGrid({controller:a});return a.view};a._loadDataGrid=function(){a.view.getDataGrid().load()};a._onactivate=function(){var b=new mx.permissions.Permission({iscID:"-1"});mx.permissions.PermissionAgent.setPermission(b,a.view);a.view.getDataGrid().load()};a.endOfClass(arguments);return a};$ns("thermalpower.views");$import("fusionChart.lib.FusionCharts");
thermalpower.views.mainView=function(){function k(a){a=i.getSync(thermalpower.mappath("~/rest/setielineresultn/getAverageDataChart"),{params:JSON.stringify({toporlast:a})});if(a.successful==!0){b.averageData=a.resultValue.items[0];if(b.averageData=="0")mx.indicate("info","\u8be5\u4e1a\u52a1\u573a\u666f\u4e0d\u5b58\u5728\u706b\u7535\u7edf\u8c03\u7535\u5382\u5b8c\u6210\u7387\u4e0e\u5e73\u5747\u8fdb\u5ea6\u504f\u5dee\u6570\u636e"),b.averageData="";a=new FusionCharts(fusionChart.mappath("$/swf/StackedBar2D.swf"),
"myChartId","100%","100%","0","1");a.setDataXML(b.averageData);d.addControl(a);a.render(d.$e.get(0))}}function m(){k(b.dropDownEditor.value)}var b=$extend(mx.views.View),l={};l.init=b.init;var i=new mx.rpc.RESTClient;b.init=function(){l.init();b.setHeight("100%");b.setWidth("100%");b.permissionID="-1";e=new mx.containers.Panel({id:"Panel1",border:"1",height:"500",title:"\u706b\u7535\u7edf\u8c03\u7535\u5382\u5b8c\u6210\u7387\u524d10\u540d"});b.addControl(e);f=new mx.containers.Panel({id:"Panel2",border:"1",
height:"60%",displayHead:!1});e.addControl(f);j=(new thermalpower.views.DataGridController).getView().getTopTenDataGrid();j.load();e.addControl(j);g=new mx.containers.Panel({id:"Panel10",border:"1",height:"500",title:"\u706b\u7535\u7edf\u8c03\u7535\u5382\u5b8c\u6210\u7387\u540e10\u540d"});b.addControl(g);h=new mx.containers.Panel({id:"Panel9",border:"1",height:"60%",displayHead:!1});g.addControl(h);var a=(new thermalpower.views.DataGridController).getView().getLastTenDataGrid();a.load();g.addControl(a);
d=new mx.containers.Panel({id:"Panel13",border:"1",height:"60%",displayHead:!1});c=new mx.containers.Panel({id:"Panel14",border:"1",height:"500"});b.dropDownEditor=new mx.editors.DropDownEditor({allowEditing:!1,displayCheckBox:!1,valueSeparator:"#",displayMember:"name",valueMember:"value",items:[{name:"\u524d\u5341\u540d",value:"topTen"},{name:"\u540e\u5341\u540d",value:"lastTen"}],onchanged:m});b.dropDownEditor.setValue("topTen","\u524d\u5341\u540d",!0);c.$e.find("#head").append("\u706b\u7535\u7edf\u8c03\u7535\u5382\u5b8c\u6210\u7387\u4e0e\u5e73\u5747\u8fdb\u5ea6\u504f\u5dee      ");
c.$e.find("#head").append(b.dropDownEditor.$e);c.addControl(d);b.addControl(c);a=(new thermalpower.views.DataGridController).getView().getAverageDataGrid();a.load();c.addControl(a);b.on("activate",b.controller._onactivate)};var e=null,f=null,j=null,g=null,h=null,c=null,d=null;b.call=function(){var a=i.getSync(thermalpower.mappath("~/rest/setielineresultn/getTopTenChart"));if(a.successful==!0){b.topTenData=a.resultValue.items[0];if(b.topTenData=="0")mx.indicate("info","\u8be5\u4e1a\u52a1\u573a\u666f\u4e0d\u5b58\u5728\u706b\u7535\u7edf\u8c03\u7535\u5382\u5b8c\u6210\u7387\u524d10\u540d\u6570\u636e"),
b.topTenData="";a=new FusionCharts(fusionChart.mappath("$/swf/StackedBar2D.swf"),"myChartId","100%","100%","0","1");a.setDataXML(b.topTenData);f.addControl(a);a.render(f.$e.get(0))}a=i.getSync(thermalpower.mappath("~/rest/setielineresultn/getLastTenChart"));if(a.successful==!0){b.lastTenData=a.resultValue.items[0];if(b.lastTenData=="0")mx.indicate("info","\u8be5\u4e1a\u52a1\u573a\u666f\u4e0d\u5b58\u5728\u706b\u7535\u7edf\u8c03\u7535\u5382\u5b8c\u6210\u7387\u540e10\u540d\u6570\u636e"),b.lastTenData=
"";a=new FusionCharts(fusionChart.mappath("$/swf/StackedBar2D.swf"),"myChartId","100%","100%","0","1");a.setDataXML(b.lastTenData);h.addControl(a);a.render(h.$e.get(0))}k("topTen")};return b.endOfClass(arguments)};$ns("thermalpower.views");thermalpower.views.mainViewController=function(){var a=$extend(mx.views.ViewController);a.getView=function(){if(a.view==null)a.view=new thermalpower.views.mainView({controller:a});return a.view};a._onactivate=function(){a.getView().call()};return a.endOfClass(arguments)};